save "$0.gp"
author = 'Christof Kälin';
watermark = "File $0.png - Generated by " . author . " at `date`";

set label 9999 watermark at screen 0.02,0.02 font "/usr/share/fonts/liberation/LiberationSans-Regular.ttf, 6"

set bmargin 3

set t push
set t png font "/usr/share/fonts/liberation/LiberationSans-Regular.ttf, 6"
set o "$0.png"
replot
set o
set t pop

watermark = ''
unset label 9999
unset bmargin

